spring:
  application:
    name: Ride_App

  data:
    mongodb:
      database: rideshare
      uri: mongodb://localhost:27017

server:
  port: 8081

jwt:
  secret: jwtsecretkeyjwtsecretkeyjwtsecret123
  expiration: 3600000
